title: Jiwei Yang
affiliation: Tsinghua University
affiliation_link: https://www.tsinghua.edu.cn/en/
position: Research Assistant
email: yangjiwei@tsinghua.vin
chinese_name: 杨济玮
keywords: world models, embodied intelligence, autonomous driving
description: Jiwei Yang's academic homepage.
github_link: https://github.com/NoctYang
cv_link: assets/Jiwei_Yang_CV.pdf
avatar: ./assets/profile.jpeg
favicon: ./assets/favicon.svg
favicon_dark: ./assets/favicon.svg
auto_dark_mode: false
font: "Serif"
enable_footnote: true
remote_theme: yaoyao-liu/minimal-light
exclude:
  - README.md
